language: node_js
node_js:
  - "0.10"

before_install:
  - npm config set spin false
  - npm config set loglevel silent
  - npm i bower grunt-cli -g

install:
  - travis_retry npm install

script:
  - npm run validate-shrinkwrap # check for vulnerable modules via nodesecurity.io
  - npm run outdated
  - npm run lint
